# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-17 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='book',
        ),
    ]
